version: "2.0"

services:
  web:
    image: "waelali115/rescuenet:latest" # Replace with your Docker Hub image
    env:
      - PORT=8000
    expose:
      - port: 8000
        as: 80
        to:
          - global

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 512Mi
        storage:
          size: 1Gi
  placement:
    akash:
      pricing:
        web:
          denom: uakt
          amount: 100

deployment:
  web:
    akash:
      profile: web
      count: 1

